=== yvesnoblet/architecture-des-systemes-dinformation/biblioXMLschemaASI.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xs:element name="bibliographie" >
        <xs:complexType>
            <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" ref="livre"/>
                    <xs:element minOccurs="0" maxOccurs="unbounded" ref="chapitrelivre"/>
                    <xs:element minOccurs="0" maxOccurs="unbounded" ref="article"/>
                    <xs:element minOccurs="0" maxOccurs="unbounded" ref="colloque"/>
                    <xs:element minOccurs="0" maxOccurs="unbounded" ref="prépublication"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="livre" >
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="auteur">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="prénom" type="xs:string"/>
                        </xs:sequence>                 
                    </xs:complexType>
                    </xs:element>
                    <xs:element name="auteurs">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="auteur" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="nom" type="xs:string"/>
                                            <xs:element name="prénom" type="xs:string"/>
                                        </xs:sequence>                 
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
                <xs:element name="titre" type="xs:string"/>
                <xs:element name="édition" type="xs:string"/>
                <xs:element name="lieu" type="xs:string"/>
                <xs:element name="année" type="xs:integer"/>
                <xs:element name="langue" type="xs:string"/>
                <xs:element name="ISBN" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="url" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="cataloguebiblio" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="chapitrelivre" >
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="auteur">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="nom" type="xs:string"/>
                                <xs:element name="prénom" type="xs:string"/>
                            </xs:sequence>                 
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="auteurs">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="auteur" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="nom" type="xs:string"/>
                                            <xs:element name="prénom" type="xs:string"/>
                                        </xs:sequence>                 
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
                <xs:element name="titrechapitre" type="xs:string"/>
                <xs:choice>
                    <xs:element name="éditeur">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="nom" type="xs:string"/>
                                <xs:element name="prénom" type="xs:string"/>
                            </xs:sequence>                 
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="éditeurs">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="éditeur" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="nom" type="xs:string"/>
                                            <xs:element name="prénom" type="xs:string"/>
                                        </xs:sequence>                 
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
                <xs:element name="titrelivre" type="xs:string"/>
                <xs:element name="édition" type="xs:string"/>
                <xs:element name="lieu" type="xs:string"/>
                <xs:element name="année" type="xs:integer"/>
                <xs:element name="nbpages" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="langue" type="xs:string"/>
                <xs:element name="DOI" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="ISBN" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="url" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="cataloguebiblio" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="article">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="auteur">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="nom" type="xs:string"/>
                                <xs:element name="prénom" type="xs:string"/>
                            </xs:sequence>                 
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="auteurs">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="auteur" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="nom" type="xs:string"/>
                                            <xs:element name="prénom" type="xs:string"/>
                                        </xs:sequence>                 
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
                <xs:element name="titre" type="xs:string"/>
                <xs:element name="revue" type="xs:string"/>
                <xs:element name="volume" minOccurs="0" maxOccurs="1"/>
                <xs:element name="numéro" minOccurs="0" maxOccurs="1"/>
                <xs:element name="année" type="xs:integer"/>
                <xs:element name="nbpages" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="langue" type="xs:string"/>
                <xs:element name="DOI" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="ISSN" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="url" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="cataloguebiblio" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="colloque">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="auteur">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="nom" type="xs:string"/>
                                <xs:element name="prénom" type="xs:string"/>
                            </xs:sequence>                 
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="auteurs">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="auteur" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="nom" type="xs:string"/>
                                            <xs:element name="prénom" type="xs:string"/>
                                        </xs:sequence>                 
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
                <xs:element name="titre" type="xs:string"/>
                <xs:choice>
                    <xs:element name="éditeur">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="nom" type="xs:string"/>
                                <xs:element name="prénom" type="xs:string"/>
                            </xs:sequence>                 
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="éditeurs">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="éditeur" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="nom" type="xs:string"/>
                                            <xs:element name="prénom" type="xs:string"/>
                                        </xs:sequence>                 
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
                <xs:element name="titrecolloque" type="xs:string"/>
                <xs:element name="édition" type="xs:string"/>
                <xs:element name="lieu" type="xs:string"/>
                <xs:element name="année" type="xs:integer"/>
                <xs:element name="nbpages" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="langue" type="xs:string"/>
                <xs:element name="DOI" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="ISBN" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="url" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="cataloguebiblio" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="prépublication">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="auteur">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="nom" type="xs:string"/>
                                <xs:element name="prénom" type="xs:string"/>
                            </xs:sequence>                 
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="auteurs">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="auteur" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="nom" type="xs:string"/>
                                            <xs:element name="prénom" type="xs:string"/>
                                        </xs:sequence>                 
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
                <xs:element name="titre" type="xs:string"/>
                <xs:element name="année" type="xs:integer"/>
                <xs:element name="nbpages" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="langue" type="xs:string"/>
                <xs:element name="identifiantarchive" type="xs:string"/>
                <xs:element name="DOI" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="dépôt" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="url" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="cataloguebiblio" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
 </xs:schema>

=== yvesnoblet/architecture-des-systemes-dinformation/biblioXMLASI.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliographie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="biblioXMLschemaASI.xsd">
    
  <livre>
      <auteurs>         
          <auteur>
               <nom>Lemberger</nom>
               <prénom>Pirmin</prénom>
          </auteur>         
          <auteur>
              <nom>Batty</nom>
              <prénom>Marc</prénom> 
          </auteur>
          <auteur>
              <nom> Morel</nom>
              <prénom>Médéric</prénom>
          </auteur>
          <auteur>
              <nom>Raffaëlli</nom>
              <prénom>Jean-Luc</prénom>
          </auteur>
      </auteurs>
      <titre>Big data et machine learning: les concepts et les outils de la data science</titre>
      <édition>Dunod</édition>
      <lieu></lieu>
      <année>2019</année>
      <langue>Français</langue>
      <ISBN>978-2-10-079037-1</ISBN>
      <url></url>
      <cataloguebiblio>BnF ISBN</cataloguebiblio>
  </livre> 
  <chapitrelivre>
      <auteurs>
          <auteur>
              <nom>Glazkova</nom>
              <prénom>Anna</prénom>               
          </auteur>
          <auteur>
              <nom>Kruzhinov</nom>
              <prénom>Valery</prénom>                
          </auteur>
          <auteur>
              <nom>Sokova</nom>
              <prénom>Zinaida</prénom>          
          </auteur>
      </auteurs>
      <titrechapitre>Automatic Text Processing for Historical Research</titrechapitre>
      <éditeurs>
          <éditeur>
              <nom>Sukhomlin</nom>
              <prénom>Vladimir</prénom> 
          </éditeur>
          <éditeur>
              <nom>Zubareva</nom>
              <prénom>Elena</prénom>               
          </éditeur>
      </éditeurs>
      <titrelivre>Modern Information Technology and IT Education</titrelivre>
      <édition>Springer International Publishing</édition>
      <lieu>Moscou</lieu>
      <année>2021</année>
      <nbpages>135-146</nbpages>
      <langue>Anglais</langue>
      <DOI>10.1007/978-3-030-78273-3</DOI>          
      <ISBN>978-3-030-78272-6</ISBN>
      <url>https://link.springer.com/10.1007/978-3-030-78273-3_14</url>
      <cataloguebiblio>DOI.org (Crossref)</cataloguebiblio>
  </chapitrelivre>  
          
  <article>
      <auteurs>
          <auteur>
              <nom>Caliskan</nom>
              <prénom>Aylin</prénom>               
          </auteur>
          <auteur>
              <nom>Bryson</nom>
              <prénom> Joanna J.</prénom>             
          </auteur>
          <auteur>
              <nom>Narayanan</nom>
              <prénom>Arvind</prénom>               
          </auteur>
      </auteurs>
      <titre>Semantics derived automatically from language corpora contain human-like biases</titre>
      <revue>Science</revue>
      <volume>356</volume>
      <numéro>6334</numéro>
      <année>2017</année>
      <nbpages>183-186</nbpages>
      <langue>Anglais</langue>
      <DOI>10.1126/science.aal4230</DOI>
      <ISSN>0036-8075</ISSN>
      <url>https://www.science.org/doi/full/10.1126/science.aal4230</url>
      <cataloguebiblio>science.org (Atypon)</cataloguebiblio>
  </article>
  <article>
      <auteurs>
          <auteur>
              <nom>Garg</nom>
              <prénom>Nikhil</prénom>              
          </auteur>
          <auteur>
              <nom>Schiebinger</nom>
              <prénom>Londa</prénom>              
          </auteur>
          <auteur>
              <nom>Jan</nom>
              <prénom>Jurafsky</prénom>               
          </auteur>
          <auteur>
              <nom>Zou</nom>
              <prénom>James</prénom>         
          </auteur>
      </auteurs>
      <titre>Word embeddings quantify 100 years of gender and ethnic stereotypes</titre>
      <revue>Proceedings of the National Academy of Sciences</revue>
      <volume>115</volume>
      <numéro>16</numéro>
      <année>2022</année>
      <nbpages>E3635-E3644</nbpages>
      <langue>Anglais</langue>
      <DOI>10.1073/pnas.1720347115</DOI>
      <ISSN> 0027-8424</ISSN>
      <url>https://www.pnas.org/doi/full/10.1073/pnas.1720347115</url>
      <cataloguebiblio>pnas.org (Atypon)</cataloguebiblio>
  </article>    
  <article>
      <auteurs>
          <auteur>
              <nom>Liebeskind</nom>
              <prénom>Chaya</prénom>              
          </auteur>
          <auteur>
              <nom>Liebeskind</nom>
              <prénom>Shmuel</prénom>              
          </auteur>
      </auteurs>
      <titre>Deep Learning for Period Classification of Historical Hebrew Texts</titre>
      <revue>Journal of Data Mining and Digital Humanities</revue>
      <volume>2020</volume>
      <numéro></numéro>
      <année>2020</année>
      <nbpages></nbpages>
      <langue>Anglais</langue>
      <DOI>10.46298/jdmdh.5864</DOI>
      <ISSN>2416-5999</ISSN>
      <url>https://hal.archives-ouvertes.fr/hal-02324617</url>
      <cataloguebiblio>HAL Archives Ouvertes</cataloguebiblio>
  </article> 
 
  <article>
      <auteurs>
          <auteur>
              <nom>Labbé</nom>
              <prénom>Cyril</prénom>              
          </auteur>
          <auteur>
              <nom>Labbé</nom>
              <prénom>Dominique</prénom> 
          </auteur>
      </auteurs>
      <titre>How to Measure the Meanings of Words? Amour in Corneille’s Work</titre>
      <revue>Language Resources and Evaluation</revue>
      <volume>39</volume>
      <numéro>4</numéro>
      <année>2005</année>
      <nbpages>335-351</nbpages>
      <langue>Anglais</langue>
      <DOI>10.1007/s10579-006-9002-8</DOI>
      <ISSN>1574-020X</ISSN>
      <url>http://link.springer.com/10.1007/s10579-006-9002-8</url>
      <cataloguebiblio>DOI.org (Crossref)</cataloguebiblio>
  </article>

  <article>
      <auteurs>
          <auteur>
              <nom>Lee</nom>
              <prénom>Kamwoo</prénom>               
          </auteur>
          <auteur>
              <nom>Braithwaite</nom>
              <prénom>Jeanine</prénom>              
          </auteur>
          <auteur>
              <nom>Atchikpa</nom>
              <prénom>Michel</prénom> 
          </auteur>
      </auteurs>
      <titre>Word embedding analysis on colonial history, present issues, and optimism toward the future in Senegal</titre>
      <revue>Computational and Mathematical Organization Theory</revue>
      <volume>27</volume>
      <numéro>3</numéro>
      <année>2021</année>
      <nbpages>343-356</nbpages>
      <langue>Anglais</langue>
      <DOI>10.1007/s10588-021-09335-y</DOI>
      <ISSN>1381-298X</ISSN>
      <url>https://link.springer.com/10.1007/s10588-021-09335-y</url>
      <cataloguebiblio>DOI.org (Crossref)</cataloguebiblio>
  </article>

  <article>
      <auteurs>
          <auteur>
              <nom>Jakhar</nom>
              <prénom>Deepak</prénom>              
          </auteur>
          <auteur>
              <nom>Kaur</nom>
              <prénom>Ishmeet</prénom>               
          </auteur>
      </auteurs>
      <titre>Artificial intelligence, machine learning and deep learning: definitions and differences</titre>
      <revue>Artificial intelligence, machine learning and deep learning: definitions and differences</revue>
      <volume>45</volume>
      <numéro>1</numéro>
      <année>2020</année>
      <nbpages>131-132</nbpages>
      <langue>Anglais</langue>
      <DOI>10.1111/ced.14029</DOI>
      <ISSN>1365-2230</ISSN>
      <url>http://onlinelibrary.wiley.com/doi/abs/10.1111/ced.14029</url>
      <cataloguebiblio>Wiley Online Library</cataloguebiblio>
  </article>
    
  <article>
      <auteurs>
          <auteur>
              <nom>Janiesch</nom>
              <prénom>Christian</prénom>               
          </auteur>
          <auteur>
              <nom>Zschech</nom>
              <prénom>Patrick</prénom>              
          </auteur>
          <auteur>
              <nom>Heinrich</nom>
              <prénom>Kai</prénom> 
          </auteur>
      </auteurs>
      <titre>Machine learning and deep learning</titre>
      <revue>Electronic Markets</revue>
      <volume>31</volume>
      <numéro>3</numéro>
      <année>2021</année>
      <nbpages>685-695</nbpages>
      <langue>Anglais</langue>
      <DOI>10.1007/s12525-021-00475-2</DOI>
      <ISSN>1019-6781</ISSN>
      <url>https://link.springer.com/10.1007/s12525-021-00475-2</url>
      <cataloguebiblio>DOI.org (Crossref)</cataloguebiblio>
  </article> 
    
  <article>
      <auteurs>
          <auteur>
              <nom>Jin</nom>
              <prénom>KyoHoon</prénom>              
          </auteur>
          <auteur>
              <nom>Wi</nom>
              <prénom>JeongA</prénom>              
          </auteur>
          <auteur>
              <nom>Kang</nom>
              <prénom>KyeongPil</prénom>              
          </auteur>
          <auteur>
              <nom>Kim</nom>
              <prénom>YoungBin</prénom>                        
          </auteur>
      </auteurs>
      <titre>Korean Historical Documents Analysis with Improved Dynamic Word Embedding</titre>
      <revue>Applied Sciences</revue>
      <volume>10</volume>
      <numéro>21</numéro>
      <année>2020</année>
      <nbpages>7939</nbpages>
      <langue>Anglais</langue>
      <DOI>10.3390/app10217939</DOI>
      <ISSN>2076-3417</ISSN>
      <url>http://www.proquest.com/docview/2534072115/abstract/63B38EE3CAE54908PQ/1</url>
      <cataloguebiblio>ProQuest</cataloguebiblio>
  </article> 
  <article>
      <auteurs>
          <auteur>
              <nom>Maulud</nom>
              <prénom> Dastan Hussen </prénom>             
          </auteur>
          <auteur>
              <nom>Zeebaree</nom>
              <prénom>Subhi R. M.</prénom>               
          </auteur>
          <auteur>
              <nom>Jacksi</nom>
              <prénom>Karwan</prénom> 
          </auteur>
          <auteur>
